### ISSUE TITLE
论文中公式2和代码是不是不太一样

### ISSUE THREAD

**Issue by Grace160** [SCoulY/MuSCLe#2]
论文中公式2和代码是不是不太一样

**Comment by SCoulY** [comment]
稍微有些不同 normalisation方式不太一样 两种方式我们都试过 不太影响结果 但代码实现的会memory efficient一点 具体可以看看SEAM里面的描述

**Comment by Zhengyang1995** [comment]
您好，首先感谢您的工作，里面的内容非常丰富。

但我对论文中的公式2 和 3及代码实现的部分也有一点疑问。
（1）代码中，是不是用SEAM的PCM替换了公式 2 呢？
（2）根据描述，公式 3计算的是'feature vectors'，但实际计算的好像不是‘feature’而是‘response’（loss_pixpro）；同样的疑惑也存在于公式6，似乎代码中计算的也不是‘feature’而是norm后的response。 
因为我看论文中用 CAM response map形容M，但用feature maps形容M'.但根据SEAM中PCM的描述的话，PCM的输出（也就是M‘）应该也是同样的modified CAM.

另外，M和M~的区别是不是一个来自crop1一个来自crop2的不同CAM？

**Comment by SCoulY** [comment]
> 您好，首先感谢您的工作，里面的内容非常丰富。
> 
> 但我对论文中的公式2 和 3及代码实现的部分也有一点疑问。 （1）代码中，是不是用SEAM的PCM替换了公式 2 呢？ （2）根据描述，公式 3计算的是'feature vectors'，但实际计算的好像不是‘feature’而是‘response’（loss_pixpro）；同样的疑惑也存在于公式6，似乎代码中计算的也不是‘feature’而是norm后的response。 因为我看论文中用 CAM response map形容M，但用feature maps形容M'.但根据SEAM中PCM的描述的话，PCM的输出（也就是M‘）应该也是同样的modified CAM.
> 
> 另外，M和M~的区别是不是一个来自crop1一个来自crop2的不同CAM？

(1): yes, our SAM implementation is based on PCM from SEAM
(2): Eq.3 and Eq.6 are caculated based on normalised feature vector or 'response' as you mentioned and are omitted in the equation. While for $M$, $M^\prime$ and $\tilde{M}$, they represent CAM from crop1, SAM from crop1 and CAM from crop2 respectively. It is better illustrated in Figure2.

**Comment by Zhengyang1995** [comment]
Okay thank you so much!
