### ISSUE TITLE
权重之间的区别

### ISSUE THREAD

**Issue by Myles091** [SCoulY/MuSCLe#8]
hi,

   打扰您了，我想知道这三个权重之间的区别:MuSCL-b7_63.35_66.6.pth,MCL_55.35_58.5.pth,IRN_pretrained.pth之间的区别。

   同时我想知道在运行python infer_mcl.py 之后生成的cam是npy的格式，要如何进行可视化呢。

谢谢！

**Comment by Myles091** [comment]
生成的events.out.tfevents.1699602379.GPU01用tensorboard打开之后显示无数据

**Comment by SCoulY** [comment]
> hi,
> 
> 打扰您了，我想知道这三个权重之间的区别:MuSCL-b7_63.35_66.6.pth,MCL_55.35_58.5.pth,IRN_pretrained.pth之间的区别。
> 
> 同时我想知道在运行python infer_mcl.py 之后生成的cam是npy的格式，要如何进行可视化呢。
> 
> 谢谢！

MuSCLe是最后segmentation network 包含MCL encoder和beacon decoder
MCL只用于生成CAM
IRN 是做CAM refinement的
infer_mcl 指定`--tblog` 可视化 新的update disable了confidence score的写入 现在的tfevent应该有CAM的正常可视化
